# Generated by Django 4.2 on 2023-05-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(default='user', max_length=20)),
                ('state', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
