# Generated by Django 4.2.1 on 2023-05-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_news'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
