# Generated by Django 4.2.1 on 2023-05-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_news_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
