# Generated by Django 4.2 on 2023-06-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, default='user', max_length=20)),
                ('state', models.BooleanField(blank=True, default=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
