# Generated by Django 4.2 on 2023-06-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
