# Generated by Django 4.2 on 2023-06-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_new_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='date',
        ),
        migrations.AddField(
            model_name='new',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
    ]
