# Generated by Django 4.2 on 2023-06-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_alter_new_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
