# Generated by Django 4.2 on 2023-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_alter_new_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.TextField(),
        ),
    ]
