# Generated by Django 4.2 on 2023-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomimage',
            name='image',
            field=models.URLField(),
        ),
    ]
