# Generated by Django 4.2 on 2023-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room_image', '0005_rename_hotel_room_hotelroomimage_hotel_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomimage',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
