# Generated by Django 4.2 on 2023-06-02 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_room', '0002_remove_hotelroom_visits_alter_hotelroom_geolocation_and_more'),
        ('user', '0003_alter_user_password_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('hotel_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_room.hotelroom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
