# Generated by Django 4.2 on 2023-06-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=200)),
                ('hotel_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_room.hotelroom')),
            ],
        ),
    ]
