# Generated by Django 4.2 on 2023-06-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroomservice',
            old_name='hotel_room_id',
            new_name='hotel_room',
        ),
    ]
