# Generated by Django 4.2 on 2023-06-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0002_remove_hotelroom_visits_alter_hotelroom_geolocation_and_more'),
        ('hotel_room_service', '0002_rename_hotel_room_id_hotelroomservice_hotel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomservice',
            name='hotel_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotel_room.hotelroom'),
        ),
    ]
