# Generated by Django 4.2 on 2023-06-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room_service', '0003_alter_hotelroomservice_hotel_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroomservice',
            old_name='hotel_room',
            new_name='hotel_room_id',
        ),
    ]
