# Generated by Django 4.2 on 2023-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room_service', '0004_rename_hotel_room_hotelroomservice_hotel_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomservice',
            name='service',
            field=models.TextField(),
        ),
    ]
