# Generated by Django 4.2 on 2023-06-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('score', models.FloatField()),
                ('description', models.TextField()),
                ('geolocation', models.CharField(max_length=300)),
                ('link', models.TextField()),
                ('discount', models.BooleanField()),
                ('visits', models.IntegerField()),
            ],
        ),
    ]
