# Generated by Django 4.2 on 2023-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='visits',
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='geolocation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='name',
            field=models.TextField(),
        ),
    ]
