# Generated by Django 4.2 on 2023-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0002_remove_hotelroom_visits_alter_hotelroom_geolocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
