# Generated by Django 4.2 on 2023-06-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0003_alter_hotelroom_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='link',
            field=models.TextField(),
        ),
    ]
